var myModule = angular.module('myApp',[]);
  myModule.config(['$routeProvider', function($routeProvider) {
  	$routeProvider.when('/main', {template: 'tpl/main.html', controller: GridCtrl});
   	$routeProvider.when('/edit', {template: 'tpl/edit.html', controller: EditCtrl});
    $routeProvider.when('/word/:category', {template: 'tpl/words.html', controller: WordCtrl});
    $routeProvider.otherwise({redirectTo: '/main'});
  }]);

  myModule.factory('categoryService', function () {
  	var categoryService = {}
  	categoryService.data = [
           {"text":"Pronoun", "hide":false},
           {"text":"Verb 1", "hide":false},
           {"text":"Verb 2", "hide":false},
           {"text":"Verb 3", "hide":false},
           {"text":"Verb 4", "hide":false},
           {"text":"Verb 5", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"Pron'Verb", "hide":false},
           {"text":"Helpers", "hide":false},
           {"text":"Number", "hide":false},
           {"text":"Colour", "hide":false},
           {"text":"Adj 1", "hide":false},
           {"text":"Adj 2", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"Preposition", "hide":false},
           {"text":"Indefinite", "hide":false},
           {"text":"People", "hide":false},
           {"text":"Adverb", "hide":false},
           {"text":"Time", "hide":false},
           {"text":"Dolch 1", "hide":false},
           {"text":"Dolch 2", "hide":false},
           {"text":"Dolch 3", "hide":false},
           {"text":"Conjunct", "hide":false},
           {"text":"Determiner", "hide":false},
           {"text":"Not", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"Interject", "hide":false},
           {"text":"Question", "hide":false},
           {"text":"ABC", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true}
        ];
        return categoryService;
  });

myModule.factory('wordService', function () {
    var wordService = {}
    wordService.data = [
           {"category":"Pronoun", "text":"I", "hide":false},
           {"category":"Pronoun", "text":"you", "hide":false},
           { "category":"Pronoun", "text":"he", "hide":false},
           { "category":"Pronoun", "text":"she", "hide":false},
           { "category":"Pronoun", "text":"it", "hide":false},
           { "category":"Pronoun", "text":"we", "hide":false},
           { "category":"Pronoun", "text":"they", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"me", "hide":false},
           { "category":"Pronoun", "text":"you", "hide":false},
           { "category":"Pronoun", "text":"him", "hide":false},
           { "category":"Pronoun", "text":"her", "hide":false},
           { "category":"Pronoun", "text":"it", "hide":false},
           { "category":"Pronoun", "text":"us", "hide":false},
           { "category":"Pronoun", "text":"them", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"mine", "hide":false},
           { "category":"Pronoun", "text":"yours", "hide":false},
           { "category":"Pronoun", "text":"his", "hide":false},
           { "category":"Pronoun", "text":"hers", "hide":false},
           { "category":"Pronoun", "text":"its", "hide":false},
           { "category":"Pronoun", "text":"ours", "hide":false},
           { "category":"Pronoun", "text":"theirs", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"my", "hide":false},
           { "category":"Pronoun", "text":"your", "hide":false},
           { "category":"Pronoun", "text":"his", "hide":false},
           { "category":"Pronoun", "text":"her", "hide":false},
           { "category":"Pronoun", "text":"its", "hide":false},
           { "category":"Pronoun", "text":"our", "hide":false},
           { "category":"Pronoun", "text":"their", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"myself", "hide":false},
           { "category":"Pronoun", "text":"yourself", "hide":false},
           { "category":"Pronoun", "text":"himself", "hide":false},
           { "category":"Pronoun", "text":"herself", "hide":false},
           { "category":"Pronoun", "text":"itself", "hide":false},
           { "category":"Pronoun", "text":"ourselves", "hide":false},
           { "category":"Pronoun", "text":"themselves", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"People", "text":"baby", "hide":false},
           { "category":"People", "text":"boy", "hide":false},
           { "category":"People", "text":"brother", "hide":false},
           { "category":"People", "text":"child", "hide":false},
           { "category":"People", "text":"children", "hide":false},
           { "category":"People", "text":"cousin", "hide":false},
           { "category":"People", "text":"Dad", "hide":false},
           { "category":"People", "text":"doctor", "hide":false},
           { "category":"People", "text":"driver", "hide":false},
           { "category":"People", "text":"family", "hide":false},
           { "category":"People", "text":"father", "hide":false},
           { "category":"People", "text":"friend", "hide":false},
           { "category":"People", "text":"friends", "hide":false},
           { "category":"People", "text":"girl", "hide":false},
           { "category":"People", "text":"girls", "hide":false},
           { "category":"People", "text":"Grandma", "hide":false},
           { "category":"People", "text":"Granddad", "hide":false},
           { "category":"People", "text":"guy", "hide":false},
           { "category":"People", "text":"man", "hide":false},
           { "category":"People", "text":"Mother", "hide":false},
           { "category":"People", "text":"Mum", "hide":false},
           { "category":"People", "text":"nurse", "hide":false},
           { "category":"People", "text":"OT", "hide":false},
           { "category":"People", "text":"people", "hide":false},
           { "category":"People", "text":"person", "hide":false},
           { "category":"People", "text":"Physio", "hide":false},
           { "category":"People", "text":"sister", "hide":false},
           { "category":"People", "text":"SLT", "hide":false},
           { "category":"People", "text":"teacher", "hide":false},
           { "category":"Indefinite", "text":"anybody", "hide":false},
           { "category":"Indefinite", "text":"anyone", "hide":false},
           { "category":"Indefinite", "text":"anything", "hide":false},
           { "category":"Indefinite", "text":"any time", "hide":false},
           { "category":"Indefinite", "text":"anyway", "hide":false},
           { "category":"Indefinite", "text":"anywhere", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"everybody", "hide":false},
           { "category":"Indefinite", "text":"everyone", "hide":false},
           { "category":"Indefinite", "text":"everything", "hide":false},
           { "category":"Indefinite", "text":"every time", "hide":false},
           { "category":"Indefinite", "text":"every way", "hide":false},
           { "category":"Indefinite", "text":"everywhere", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"nobody", "hide":false},
           { "category":"Indefinite", "text":"no one", "hide":false},
           { "category":"Indefinite", "text":"nothing", "hide":false},
           { "category":"Indefinite", "text":"no time", "hide":false},
           { "category":"Indefinite", "text":"no way", "hide":false},
           { "category":"Indefinite", "text":"nowhere", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"somebody", "hide":false},
           { "category":"Indefinite", "text":"someone", "hide":false},
           { "category":"Indefinite", "text":"something", "hide":false},
           { "category":"Indefinite", "text":"sometimes", "hide":false},
           { "category":"Indefinite", "text":"some way", "hide":false},
           { "category":"Indefinite", "text":"somewhere", "hide":false},
           { "category":"Pron'Verb", "text":"I'm", "hide":false},
           { "category":"Pron'Verb", "text":"you're", "hide":false},
           { "category":"Pron'Verb", "text":"he's", "hide":false},
           { "category":"Pron'Verb", "text":"she's", "hide":false},
           { "category":"Pron'Verb", "text":"it's", "hide":false},
           { "category":"Pron'Verb", "text":"we're", "hide":false},
           { "category":"Pron'Verb", "text":"they're", "hide":false},
           { "category":"Pron'Verb", "text":"", "hide":false},
           { "category":"Pron'Verb", "text":"I've", "hide":false},
           { "category":"Pron'Verb", "text":"you've", "hide":false},
           { "category":"Pron'Verb", "text":"he's", "hide":false},
           { "category":"Pron'Verb", "text":"she's", "hide":false},
           { "category":"Pron'Verb", "text":"it's", "hide":false},
           { "category":"Pron'Verb", "text":"we've", "hide":false},
           { "category":"Pron'Verb", "text":"they've", "hide":false},
           { "category":"Pron'Verb", "text":"", "hide":false},
           { "category":"Pron'Verb", "text":"I'd", "hide":false},
           { "category":"Pron'Verb", "text":"you'd", "hide":false},
           { "category":"Pron'Verb", "text":"he'd", "hide":false},
           { "category":"Pron'Verb", "text":"she'd", "hide":false},
           { "category":"Pron'Verb", "text":"it'd", "hide":false},
           { "category":"Pron'Verb", "text":"we'd", "hide":false},
           { "category":"Pron'Verb", "text":"they'd", "hide":false},
           { "category":"Pron'Verb", "text":"", "hide":false},
           { "category":"Pron'Verb", "text":"I'll", "hide":false},
           { "category":"Pron'Verb", "text":"you'll", "hide":false},
           { "category":"Pron'Verb", "text":"he'll", "hide":false},
           { "category":"Pron'Verb", "text":"she'll", "hide":false},
           { "category":"Pron'Verb", "text":"it'll", "hide":false},
           { "category":"Pron'Verb", "text":"we'll", "hide":false},
           { "category":"Pron'Verb", "text":"they'll", "hide":false}
        ];
        return wordService;
  });