var myModule = angular.module('myApp',[]);
  myModule.config(['$routeProvider', function($routeProvider) {
  	$routeProvider.when('/main', {template: 'tpl/main.html', controller: GridCtrl});
   	$routeProvider.when('/edit', {template: 'tpl/edit.html', controller: EditCtrl});
    $routeProvider.when('/word/:category', {template: 'tpl/words.html', controller: WordCtrl});
    $routeProvider.otherwise({redirectTo: '/main'});
  }]);

  myModule.factory('categoryService', function () {
  	var categoryService = {}
  	categoryService.data = [
           {"text":"Pronoun", "hide":false},
           {"text":"Verb 1", "hide":false},
           {"text":"Verb 2", "hide":false},
           {"text":"Verb 3", "hide":false},
           {"text":"Verb 4", "hide":false},
           {"text":"Verb 5", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"Pron'Verb", "hide":false},
           {"text":"Helpers", "hide":false},
           {"text":"Number", "hide":false},
           {"text":"Colour", "hide":false},
           {"text":"Adj 1", "hide":false},
           {"text":"Adj 2", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"Preposition", "hide":false},
           {"text":"Indefinite", "hide":false},
           {"text":"People", "hide":false},
           {"text":"Adverb", "hide":false},
           {"text":"Time", "hide":false},
           {"text":"Dolch 1", "hide":false},
           {"text":"Dolch 2", "hide":false},
           {"text":"Dolch 3", "hide":false},
           {"text":"Conjunct", "hide":false},
           {"text":"Determiner", "hide":false},
           {"text":"Not", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"Interject", "hide":false},
           {"text":"Question", "hide":false},
           {"text":"ABC", "hide":false},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true},
           {"text":"", "hide":true}
        ];
        return categoryService;
  });

myModule.factory('wordService', function () {
    var wordService = {}
    wordService.data = [
           {"category":"Pronoun", "text":"I", "hide":false},
           {"category":"Pronoun", "text":"you", "hide":false},
           { "category":"Pronoun", "text":"he", "hide":false},
           { "category":"Pronoun", "text":"she", "hide":false},
           { "category":"Pronoun", "text":"it", "hide":false},
           { "category":"Pronoun", "text":"we", "hide":false},
           { "category":"Pronoun", "text":"they", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"me", "hide":false},
           { "category":"Pronoun", "text":"you", "hide":false},
           { "category":"Pronoun", "text":"him", "hide":false},
           { "category":"Pronoun", "text":"her", "hide":false},
           { "category":"Pronoun", "text":"it", "hide":false},
           { "category":"Pronoun", "text":"us", "hide":false},
           { "category":"Pronoun", "text":"them", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"mine", "hide":false},
           { "category":"Pronoun", "text":"yours", "hide":false},
           { "category":"Pronoun", "text":"his", "hide":false},
           { "category":"Pronoun", "text":"hers", "hide":false},
           { "category":"Pronoun", "text":"its", "hide":false},
           { "category":"Pronoun", "text":"ours", "hide":false},
           { "category":"Pronoun", "text":"theirs", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"my", "hide":false},
           { "category":"Pronoun", "text":"your", "hide":false},
           { "category":"Pronoun", "text":"his", "hide":false},
           { "category":"Pronoun", "text":"her", "hide":false},
           { "category":"Pronoun", "text":"its", "hide":false},
           { "category":"Pronoun", "text":"our", "hide":false},
           { "category":"Pronoun", "text":"their", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"Pronoun", "text":"myself", "hide":false},
           { "category":"Pronoun", "text":"yourself", "hide":false},
           { "category":"Pronoun", "text":"himself", "hide":false},
           { "category":"Pronoun", "text":"herself", "hide":false},
           { "category":"Pronoun", "text":"itself", "hide":false},
           { "category":"Pronoun", "text":"ourselves", "hide":false},
           { "category":"Pronoun", "text":"themselves", "hide":false},
           { "category":"Pronoun", "text":"", "hide":true},
           { "category":"People", "text":"baby", "hide":false},
           { "category":"People", "text":"boy", "hide":false},
           { "category":"People", "text":"brother", "hide":false},
           { "category":"People", "text":"child", "hide":false},
           { "category":"People", "text":"children", "hide":false},
           { "category":"People", "text":"cousin", "hide":false},
           { "category":"People", "text":"Dad", "hide":false},
           { "category":"People", "text":"doctor", "hide":false},
           { "category":"People", "text":"driver", "hide":false},
           { "category":"People", "text":"family", "hide":false},
           { "category":"People", "text":"father", "hide":false},
           { "category":"People", "text":"friend", "hide":false},
           { "category":"People", "text":"friends", "hide":false},
           { "category":"People", "text":"girl", "hide":false},
           { "category":"People", "text":"girls", "hide":false},
           { "category":"People", "text":"Grandma", "hide":false},
           { "category":"People", "text":"Granddad", "hide":false},
           { "category":"People", "text":"guy", "hide":false},
           { "category":"People", "text":"man", "hide":false},
           { "category":"People", "text":"Mother", "hide":false},
           { "category":"People", "text":"Mum", "hide":false},
           { "category":"People", "text":"nurse", "hide":false},
           { "category":"People", "text":"OT", "hide":false},
           { "category":"People", "text":"people", "hide":false},
           { "category":"People", "text":"person", "hide":false},
           { "category":"People", "text":"Physio", "hide":false},
           { "category":"People", "text":"sister", "hide":false},
           { "category":"People", "text":"SLT", "hide":false},
           { "category":"People", "text":"teacher", "hide":false},
           { "category":"Indefinite", "text":"anybody", "hide":false},
           { "category":"Indefinite", "text":"anyone", "hide":false},
           { "category":"Indefinite", "text":"anything", "hide":false},
           { "category":"Indefinite", "text":"any time", "hide":false},
           { "category":"Indefinite", "text":"anyway", "hide":false},
           { "category":"Indefinite", "text":"anywhere", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"everybody", "hide":false},
           { "category":"Indefinite", "text":"everyone", "hide":false},
           { "category":"Indefinite", "text":"everything", "hide":false},
           { "category":"Indefinite", "text":"every time", "hide":false},
           { "category":"Indefinite", "text":"every way", "hide":false},
           { "category":"Indefinite", "text":"everywhere", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"nobody", "hide":false},
           { "category":"Indefinite", "text":"no one", "hide":false},
           { "category":"Indefinite", "text":"nothing", "hide":false},
           { "category":"Indefinite", "text":"no time", "hide":false},
           { "category":"Indefinite", "text":"no way", "hide":false},
           { "category":"Indefinite", "text":"nowhere", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"", "hide":false},
           { "category":"Indefinite", "text":"somebody", "hide":false},
           { "category":"Indefinite", "text":"someone", "hide":false},
           { "category":"Indefinite", "text":"something", "hide":false},
           { "category":"Indefinite", "text":"sometimes", "hide":false},
           { "category":"Indefinite", "text":"some way", "hide":false},
           { "category":"Indefinite", "text":"somewhere", "hide":false},
           { "category":"Pron'Verb", "text":"I'm", "hide":false},
           { "category":"Pron'Verb", "text":"you're", "hide":false},
           { "category":"Pron'Verb", "text":"he's", "hide":false},
           { "category":"Pron'Verb", "text":"she's", "hide":false},
           { "category":"Pron'Verb", "text":"it's", "hide":false},
           { "category":"Pron'Verb", "text":"we're", "hide":false},
           { "category":"Pron'Verb", "text":"they're", "hide":false},
           { "category":"Pron'Verb", "text":"", "hide":false},
           { "category":"Pron'Verb", "text":"I've", "hide":false},
           { "category":"Pron'Verb", "text":"you've", "hide":false},
           { "category":"Pron'Verb", "text":"he's", "hide":false},
           { "category":"Pron'Verb", "text":"she's", "hide":false},
           { "category":"Pron'Verb", "text":"it's", "hide":false},
           { "category":"Pron'Verb", "text":"we've", "hide":false},
           { "category":"Pron'Verb", "text":"they've", "hide":false},
           { "category":"Pron'Verb", "text":"", "hide":false},
           { "category":"Pron'Verb", "text":"I'd", "hide":false},
           { "category":"Pron'Verb", "text":"you'd", "hide":false},
           { "category":"Pron'Verb", "text":"he'd", "hide":false},
           { "category":"Pron'Verb", "text":"she'd", "hide":false},
           { "category":"Pron'Verb", "text":"it'd", "hide":false},
           { "category":"Pron'Verb", "text":"we'd", "hide":false},
           { "category":"Pron'Verb", "text":"they'd", "hide":false},
           { "category":"Pron'Verb", "text":"", "hide":false},
           { "category":"Pron'Verb", "text":"I'll", "hide":false},
           { "category":"Pron'Verb", "text":"you'll", "hide":false},
           { "category":"Pron'Verb", "text":"he'll", "hide":false},
           { "category":"Pron'Verb", "text":"she'll", "hide":false},
           { "category":"Pron'Verb", "text":"it'll", "hide":false},
           { "category":"Pron'Verb", "text":"we'll", "hide":false},
           { "category":"Pron'Verb", "text":"they'll", "hide":false},
           { "category":"Helpers", "text":"am", "hide":false},
           { "category":"Helpers", "text":"are", "hide":false},
           { "category":"Helpers", "text":"aren't", "hide":false},
           { "category":"Helpers", "text":"be", "hide":false},
           { "category":"Helpers", "text":"been", "hide":false},
           { "category":"Helpers", "text":"being", "hide":false},
           { "category":"Helpers", "text":"can", "hide":false},
           { "category":"Helpers", "text":"can't", "hide":false},
           { "category":"Helpers", "text":"could", "hide":false},
           { "category":"Helpers", "text":"couldn't", "hide":false},
           { "category":"Helpers", "text":"did", "hide":false},
           { "category":"Helpers", "text":"didn't", "hide":false},
           { "category":"Helpers", "text":"do", "hide":false},
           { "category":"Helpers", "text":"does", "hide":false},
           { "category":"Helpers", "text":"doesn't", "hide":false},
           { "category":"Helpers", "text":"don't", "hide":false},
           { "category":"Helpers", "text":"had", "hide":false},
           { "category":"Helpers", "text":"has", "hide":false},
           { "category":"Helpers", "text":"have", "hide":false},
           { "category":"Helpers", "text":"haven't", "hide":false},
           { "category":"Helpers", "text":"is", "hide":false},
           { "category":"Helpers", "text":"isn't", "hide":false},
           { "category":"Helpers", "text":"may", "hide":false},
           { "category":"Helpers", "text":"might", "hide":false},
           { "category":"Helpers", "text":"will", "hide":false},
           { "category":"Helpers", "text":"won't", "hide":false},
           { "category":"Helpers", "text":"would", "hide":false},
           { "category":"Helpers", "text":"wouldn't", "hide":false},
           { "category":"Helpers", "text":"Not", "hide":false},
           { "category":"Verb 1", "text":"ask", "hide":false},
           { "category":"Verb 1", "text":"asked", "hide":false},
           { "category":"Verb 1", "text":"believe", "hide":false},
           { "category":"Verb 1", "text":"bet", "hide":false},
           { "category":"Verb 1", "text":"bit", "hide":false},
           { "category":"Verb 1", "text":"bite", "hide":false},
           { "category":"Verb 1", "text":"borrow", "hide":false},
           { "category":"Verb 1", "text":"bought", "hide":false},
           { "category":"Verb 1", "text":"break", "hide":false},
           { "category":"Verb 1", "text":"bring", "hide":false},
           { "category":"Verb 1", "text":"bringing", "hide":false},
           { "category":"Verb 1", "text":"brings", "hide":false},
           { "category":"Verb 1", "text":"broke", "hide":false},
           { "category":"Verb 1", "text":"broken", "hide":false},
           { "category":"Verb 1", "text":"brought", "hide":false},
           { "category":"Verb 1", "text":"build", "hide":false},
           { "category":"Verb 1", "text":"building", "hide":false},
           { "category":"Verb 1", "text":"buy", "hide":false},
           { "category":"Verb 1", "text":"call", "hide":false},
           { "category":"Verb 1", "text":"called", "hide":false},
           { "category":"Verb 1", "text":"came", "hide":false},
           { "category":"Verb 1", "text":"care", "hide":false},
           { "category":"Verb 1", "text":"carry", "hide":false},
           { "category":"Verb 1", "text":"catch", "hide":false},
           { "category":"Verb 1", "text":"change", "hide":false},
           { "category":"Verb 1", "text":"charge", "hide":false},
           { "category":"Verb 1", "text":"cheat", "hide":false},
           { "category":"Verb 1", "text":"clean", "hide":false},
           { "category":"Verb 1", "text":"climb", "hide":false},
           { "category":"Verb 1", "text":"close", "hide":false},
           { "category":"Verb 1", "text":"colour", "hide":false},
           { "category":"Verb 1", "text":"come", "hide":false},
           { "category":"Verb 1", "text":"comes", "hide":false},
           { "category":"Verb 1", "text":"coming", "hide":false},
           { "category":"Verb 1", "text":"cook", "hide":false},
           { "category":"Verb 1", "text":"count", "hide":false},
           { "category":"Verb 1", "text":"cry", "hide":false},
           { "category":"Verb 1", "text":"cut", "hide":false},
           { "category":"Verb 1", "text":"dance", "hide":false},
           { "category":"Verb 1", "text":"doing", "hide":false},
           { "category":"Verb 2", "text":"done", "hide":false},
           { "category":"Verb 2", "text":"draw", "hide":false},
           { "category":"Verb 2", "text":"dress", "hide":false},
           { "category":"Verb 2", "text":"drink", "hide":false},
           { "category":"Verb 2", "text":"drive", "hide":false},
           { "category":"Verb 2", "text":"eat", "hide":false},
           { "category":"Verb 2", "text":"eating", "hide":false},
           { "category":"Verb 2", "text":"end", "hide":false},
           { "category":"Verb 2", "text":"excite", "hide":false},
           { "category":"Verb 2", "text":"fall", "hide":false},
           { "category":"Verb 2", "text":"feel", "hide":false},
           { "category":"Verb 2", "text":"fell", "hide":false},
           { "category":"Verb 2", "text":"felt", "hide":false},
           { "category":"Verb 2", "text":"find", "hide":false},
           { "category":"Verb 2", "text":"finish", "hide":false},
           { "category":"Verb 2", "text":"finished", "hide":false},
           { "category":"Verb 2", "text":"fix", "hide":false},
           { "category":"Verb 2", "text":"fixed", "hide":false},
           { "category":"Verb 2", "text":"fly", "hide":false},
           { "category":"Verb 2", "text":"follow", "hide":false},
           { "category":"Verb 2", "text":"forget", "hide":false},
           { "category":"Verb 2", "text":"found", "hide":false},
           { "category":"Verb 2", "text":"get", "hide":false},
           { "category":"Verb 2", "text":"gets", "hide":false},
           { "category":"Verb 2", "text":"getting", "hide":false},
           { "category":"Verb 2", "text":"give", "hide":false},
           { "category":"Verb 2", "text":"go", "hide":false},
           { "category":"Verb 2", "text":"goes", "hide":false},
           { "category":"Verb 2", "text":"going", "hide":false},
           { "category":"Verb 2", "text":"gonna", "hide":false},
           { "category":"Verb 2", "text":"gone", "hide":false},
           { "category":"Verb 2", "text":"got", "hide":false},
           { "category":"Verb 2", "text":"guess", "hide":false},
           { "category":"Verb 2", "text":"hate", "hide":false},
           { "category":"Verb 2", "text":"hear", "hide":false},
           { "category":"Verb 2", "text":"helop", "hide":false},
           { "category":"Verb 2", "text":"hide", "hide":false},
           { "category":"Verb 2", "text":"hit", "hide":false},
           { "category":"Verb 2", "text":"hold", "hide":false},
           { "category":"Verb 2", "text":"hug", "hide":false},
           { "category":"Verb 3", "text":"hurry", "hide":false},
           { "category":"Verb 3", "text":"hurt", "hide":false},
           { "category":"Verb 3", "text":"imagine", "hide":false},
           { "category":"Verb 3", "text":"join", "hide":false},
           { "category":"Verb 3", "text":"joke", "hide":false},
           { "category":"Verb 3", "text":"jump", "hide":false},
           { "category":"Verb 3", "text":"jumped", "hide":false},
           { "category":"Verb 3", "text":"jumping", "hide":false},
           { "category":"Verb 3", "text":"keep", "hide":false},
           { "category":"Verb 3", "text":"kick", "hide":false},
           { "category":"Verb 3", "text":"kiss", "hide":false},
           { "category":"Verb 3", "text":"knew", "hide":false},
           { "category":"Verb 3", "text":"know", "hide":false},
           { "category":"Verb 3", "text":"knowing", "hide":false},
           { "category":"Verb 3", "text":"laugh", "hide":false},
           { "category":"Verb 3", "text":"lay", "hide":false},
           { "category":"Verb 3", "text":"learn", "hide":false},
           { "category":"Verb 3", "text":"leave", "hide":false},
           { "category":"Verb 3", "text":"leaves", "hide":false},
           { "category":"Verb 3", "text":"left", "hide":false},
           { "category":"Verb 3", "text":"let", "hide":false},
           { "category":"Verb 3", "text":"lift", "hide":false},
           { "category":"Verb 3", "text":"light", "hide":false},
           { "category":"Verb 3", "text":"like", "hide":false},
           { "category":"Verb 3", "text":"likes", "hide":false},
           { "category":"Verb 3", "text":"liking", "hide":false},
           { "category":"Verb 3", "text":"listen", "hide":false},
           { "category":"Verb 3", "text":"live", "hide":false},
           { "category":"Verb 3", "text":"look", "hide":false},
           { "category":"Verb 3", "text":"looking", "hide":false},
           { "category":"Verb 3", "text":"lost", "hide":false},
           { "category":"Verb 3", "text":"love", "hide":false},
           { "category":"Verb 3", "text":"made", "hide":false},
           { "category":"Verb 3", "text":"make", "hide":false},
           { "category":"Verb 3", "text":"mean", "hide":false},
           { "category":"Verb 3", "text":"meant", "hide":false},
           { "category":"Verb 3", "text":"meet", "hide":false},
           { "category":"Verb 3", "text":"mind", "hide":false},
           { "category":"Verb 3", "text":"miss", "hide":false},
           { "category":"Verb 3", "text":"move", "hide":false},
           { "category":"Verb 4", "text":"named", "hide":false},
           { "category":"Verb 4", "text":"need", "hide":false},
           { "category":"Verb 4", "text":"open", "hide":false},
           { "category":"Verb 4", "text":"own", "hide":false},
           { "category":"Verb 4", "text":"paint", "hide":false},
           { "category":"Verb 4", "text":"pass", "hide":false},
           { "category":"Verb 4", "text":"pick", "hide":false},
           { "category":"Verb 4", "text":"play", "hide":false},
           { "category":"Verb 4", "text":"pretend", "hide":false},
           { "category":"Verb 4", "text":"pour", "hide":false},
           { "category":"Verb 4", "text":"pull", "hide":false},
           { "category":"Verb 4", "text":"push", "hide":false},
           { "category":"Verb 4", "text":"put", "hide":false},
           { "category":"Verb 4", "text":"quit", "hide":false},
           { "category":"Verb 4", "text":"rain", "hide":false},
           { "category":"Verb 4", "text":"read", "hide":false},
           { "category":"Verb 4", "text":"reading", "hide":false},
           { "category":"Verb 4", "text":"relax", "hide":false},
           { "category":"Verb 4", "text":"remember", "hide":false},
           { "category":"Verb 4", "text":"rest", "hide":false},
           { "category":"Verb 4", "text":"ride", "hide":false},
           { "category":"Verb 4", "text":"run", "hide":false},
           { "category":"Verb 4", "text":"say", "hide":false},
           { "category":"Verb 4", "text":"said", "hide":false},
           { "category":"Verb 4", "text":"sat", "hide":false},
           { "category":"Verb 4", "text":"saw", "hide":false},
           { "category":"Verb 4", "text":"scream", "hide":false},
           { "category":"Verb 4", "text":"see", "hide":false},
           { "category":"Verb 4", "text":"share", "hide":false},
           { "category":"Verb 4", "text":"shout", "hide":false},
           { "category":"Verb 4", "text":"show", "hide":false},
           { "category":"Verb 4", "text":"shut", "hide":false},
           { "category":"Verb 4", "text":"sing", "hide":false},
           { "category":"Verb 4", "text":"sit", "hide":false},
           { "category":"Verb 4", "text":"sleep", "hide":false},
           { "category":"Verb 4", "text":"smile", "hide":false},
           { "category":"Verb 4", "text":"spelling", "hide":false},
           { "category":"Verb 4", "text":"stand", "hide":false},
           { "category":"Verb 4", "text":"start", "hide":false},
           { "category":"Verb 4", "text":"started", "hide":false},
           { "category":"Verb 5", "text":"stay", "hide":false},
           { "category":"Verb 5", "text":"stop", "hide":false},
           { "category":"Verb 5", "text":"store", "hide":false},
           { "category":"Verb 5", "text":"take", "hide":false},
           { "category":"Verb 5", "text":"talk", "hide":false},
           { "category":"Verb 5", "text":"teach", "hide":false},
           { "category":"Verb 5", "text":"tell", "hide":false},
           { "category":"Verb 5", "text":"throw", "hide":false},
           { "category":"Verb 5", "text":"took", "hide":false},
           { "category":"Verb 5", "text":"told", "hide":false},
           { "category":"Verb 5", "text":"try", "hide":false},
           { "category":"Verb 5", "text":"trying", "hide":false},
           { "category":"Verb 5", "text":"turn", "hide":false},
           { "category":"Verb 5", "text":"understand", "hide":false},
           { "category":"Verb 5", "text":"use", "hide":false},
           { "category":"Verb 5", "text":"used", "hide":false},
           { "category":"Verb 5", "text":"visit", "hide":false},
           { "category":"Verb 5", "text":"wait", "hide":false},
           { "category":"Verb 5", "text":"walk", "hide":false},
           { "category":"Verb 5", "text":"want", "hide":false},
           { "category":"Verb 5", "text":"wanted", "hide":false},
           { "category":"Verb 5", "text":"wants", "hide":false},
           { "category":"Verb 5", "text":"wash", "hide":false},
           { "category":"Verb 5", "text":"watch", "hide":false},
           { "category":"Verb 5", "text":"wear", "hide":false},
           { "category":"Verb 5", "text":"went", "hide":false},
           { "category":"Verb 5", "text":"work", "hide":false},
           { "category":"Verb 5", "text":"working", "hide":false},
           { "category":"Verb 5", "text":"write", "hide":false},
           { "category":"Verb 5", "text":"yell", "hide":false},
           { "category":"Adverb", "text":"again", "hide":false},
           { "category":"Adverb", "text":"almost", "hide":false},
           { "category":"Adverb", "text":"already", "hide":false},
           { "category":"Adverb", "text":"alright", "hide":false},
           { "category":"Adverb", "text":"also", "hide":false},
           { "category":"Adverb", "text":"always", "hide":false},
           { "category":"Adverb", "text":"away", "hide":false},
           { "category":"Adverb", "text":"backward", "hide":false},
           { "category":"Adverb", "text":"else", "hide":false},
           { "category":"Adverb", "text":"ever", "hide":false},
           { "category":"Adverb", "text":"far", "hide":false},
           { "category":"Adverb", "text":"forward", "hide":false},
           { "category":"Adverb", "text":"friendly", "hide":false},
           { "category":"Adverb", "text":"here", "hide":false},
           { "category":"Adverb", "text":"here's", "hide":false},
           { "category":"Adverb", "text":"indoors", "hide":false},
           { "category":"Adverb", "text":"just", "hide":false},
           { "category":"Adverb", "text":"much", "hide":false},
           { "category":"Adverb", "text":"never", "hide":false},
           { "category":"Adverb", "text":"not", "hide":false},
           { "category":"Adverb", "text":"now", "hide":false},
           { "category":"Adverb", "text":"often", "hide":false},
           { "category":"Adverb", "text":"once", "hide":false},
           { "category":"Adverb", "text":"outdoors", "hide":false},
           { "category":"Adverb", "text":"ready", "hide":false},
           { "category":"Adverb", "text":"really", "hide":false},
           { "category":"Adverb", "text":"so", "hide":false},
           { "category":"Adverb", "text":"soon", "hide":false},
           { "category":"Adverb", "text":"then", "hide":false},
           { "category":"Adverb", "text":"there", "hide":false},
           { "category":"Adverb", "text":"there's", "hide":false},
           { "category":"Adverb", "text":"today", "hide":false},
           { "category":"Adverb", "text":"together", "hide":false},
           { "category":"Adverb", "text":"tomorrow", "hide":false},
           { "category":"Adverb", "text":"tonight", "hide":false},
           { "category":"Adverb", "text":"twice", "hide":false},
           { "category":"Adverb", "text":"very", "hide":false},
           { "category":"Adverb", "text":"while", "hide":false},
           { "category":"Adverb", "text":"yesterday", "hide":false},
           { "category":"Adverb", "text":"yet", "hide":false},
           { "category":"Time", "text":"morning", "hide":false},
           { "category":"Time", "text":"afternoon", "hide":false},
           { "category":"Time", "text":"noon", "hide":false},
           { "category":"Time", "text":"night", "hide":false},
           { "category":"Time", "text":"evening", "hide":false},
           { "category":"Time", "text":"moment", "hide":false},
           { "category":"Time", "text":"second", "hide":false},
           { "category":"Time", "text":"minute", "hide":false},
           { "category":"Time", "text":"hour", "hide":false},
           { "category":"Time", "text":"o'clock", "hide":false},
           { "category":"Time", "text":"day", "hide":false},
           { "category":"Time", "text":"week", "hide":false},
           { "category":"Time", "text":"weekend", "hide":false},
           { "category":"Time", "text":"month", "hide":false},
           { "category":"Time", "text":"year", "hide":false},
           { "category":"Time", "text":"Easter", "hide":false},
           { "category":"Time", "text":"Monday", "hide":false},
           { "category":"Time", "text":"Tuesday", "hide":false},
           { "category":"Time", "text":"Wednesday", "hide":false},
           { "category":"Time", "text":"Thursday", "hide":false},
           { "category":"Time", "text":"Friday", "hide":false},
           { "category":"Time", "text":"Saturday", "hide":false},
           { "category":"Time", "text":"Sunday", "hide":false},
           { "category":"Time", "text":"Christmas", "hide":false},
           { "category":"Time", "text":"January", "hide":false},
           { "category":"Time", "text":"February", "hide":false},
           { "category":"Time", "text":"March", "hide":false},
           { "category":"Time", "text":"April", "hide":false},
           { "category":"Time", "text":"May", "hide":false},
           { "category":"Time", "text":"June", "hide":false},
           { "category":"Time", "text":"July", "hide":false},
           { "category":"Time", "text":"August", "hide":false},
           { "category":"Time", "text":"September", "hide":false},
           { "category":"Time", "text":"October", "hide":false},
           { "category":"Time", "text":"November", "hide":false},
           { "category":"Time", "text":"December", "hide":false},
           { "category":"Time", "text":"winter", "hide":false},
           { "category":"Time", "text":"spring", "hide":false},
           { "category":"Time", "text":"summer", "hide":false},
           { "category":"Time", "text":"autumn", "hide":false},
           { "category":"Adj 1", "text":"afraid", "hide":false},
           { "category":"Adj 1", "text":"angry", "hide":false},
           { "category":"Adj 1", "text":"another", "hide":false},
           { "category":"Adj 1", "text":"bad", "hide":false},
           { "category":"Adj 1", "text":"beautiful", "hide":false},
           { "category":"Adj 1", "text":"best", "hide":false},
           { "category":"Adj 1", "text":"better", "hide":false},
           { "category":"Adj 1", "text":"big", "hide":false},
           { "category":"Adj 1", "text":"bored", "hide":false},
           { "category":"Adj 1", "text":"busy", "hide":false},
           { "category":"Adj 1", "text":"clean", "hide":false},
           { "category":"Adj 1", "text":"cold", "hide":false},
           { "category":"Adj 1", "text":"dark", "hide":false},
           { "category":"Adj 1", "text":"dead", "hide":false},
           { "category":"Adj 1", "text":"different", "hide":false},
           { "category":"Adj 1", "text":"dirty", "hide":false},
           { "category":"Adj 1", "text":"dry", "hide":false},
           { "category":"Adj 1", "text":"dumb", "hide":false},
           { "category":"Adj 1", "text":"early", "hide":false},
           { "category":"Adj 1", "text":"easy", "hide":false},
           { "category":"Adj 1", "text":"enough", "hide":false},
           { "category":"Adj 1", "text":"even", "hide":false},
           { "category":"Adj 1", "text":"fast", "hide":false},
           { "category":"Adj 1", "text":"favourite", "hide":false},
           { "category":"Adj 1", "text":"fine", "hide":false},
           { "category":"Adj 1", "text":"first", "hide":false},
           { "category":"Adj 1", "text":"free", "hide":false},
           { "category":"Adj 1", "text":"full", "hide":false},
           { "category":"Adj 1", "text":"funny", "hide":false},
           { "category":"Adj 1", "text":"good", "hide":false},
           { "category":"Adj 1", "text":"happy", "hide":false},
           { "category":"Adj 1", "text":"hard", "hide":false},
           { "category":"Adj 1", "text":"high", "hide":false},
           { "category":"Adj 1", "text":"hot", "hide":false},
           { "category":"Adj 1", "text":"hungry", "hide":false},
           { "category":"Adj 1", "text":"important", "hide":false},
           { "category":"Adj 1", "text":"kind", "hide":false},
           { "category":"Adj 1", "text":"last", "hide":false},
           { "category":"Adj 1", "text":"late", "hide":false},
           { "category":"Adj 1", "text":"later", "hide":false},
           { "category":"Adj 2", "text":"light", "hide":false},
           { "category":"Adj 2", "text":"little", "hide":false},
           { "category":"Adj 2", "text":"lonely", "hide":false},
           { "category":"Adj 2", "text":"long", "hide":false},
           { "category":"Adj 2", "text":"lot", "hide":false},
           { "category":"Adj 2", "text":"lots", "hide":false},
           { "category":"Adj 2", "text":"low", "hide":false},
           { "category":"Adj 2", "text":"mad", "hide":false},
           { "category":"Adj 2", "text":"many", "hide":false},
           { "category":"Adj 2", "text":"mean", "hide":false},
           { "category":"Adj 2", "text":"medium", "hide":false},
           { "category":"Adj 2", "text":"messy", "hide":false},
           { "category":"Adj 2", "text":"more", "hide":false},
           { "category":"Adj 2", "text":"most", "hide":false},
           { "category":"Adj 2", "text":"naughty", "hide":false},
           { "category":"Adj 2", "text":"new", "hide":false},
           { "category":"Adj 2", "text":"next", "hide":false},
           { "category":"Adj 2", "text":"nice", "hide":false},
           { "category":"Adj 2", "text":"old", "hide":false},
           { "category":"Adj 2", "text":"only", "hide":false},
           { "category":"Adj 2", "text":"other", "hide":false},
           { "category":"Adj 2", "text":"pretty", "hide":false},
           { "category":"Adj 2", "text":"quiet", "hide":false},
           { "category":"Adj 2", "text":"real", "hide":false},
           { "category":"Adj 2", "text":"sad", "hide":false},
           { "category":"Adj 2", "text":"same", "hide":false},
           { "category":"Adj 2", "text":"short", "hide":false},
           { "category":"Adj 2", "text":"sick", "hide":false},
           { "category":"Adj 2", "text":"silly", "hide":false},
           { "category":"Adj 2", "text":"slow", "hide":false},
           { "category":"Adj 2", "text":"small", "hide":false},
           { "category":"Adj 2", "text":"sore", "hide":false},
           { "category":"Adj 2", "text":"still", "hide":false},
           { "category":"Adj 2", "text":"tall", "hide":false},
           { "category":"Adj 2", "text":"thirsty", "hide":false},
           { "category":"Adj 2", "text":"tired", "hide":false},
           { "category":"Adj 2", "text":"too", "hide":false},
           { "category":"Adj 2", "text":"weak", "hide":false},
           { "category":"Adj 2", "text":"wet", "hide":false},
           { "category":"Adj 2", "text":"whole", "hide":false},
           { "category":"Number", "text":"one", "hide":false},
           { "category":"Number", "text":"two", "hide":false},
           { "category":"Number", "text":"three", "hide":false},
           { "category":"Number", "text":"four", "hide":false},
           { "category":"Number", "text":"five", "hide":false},
           { "category":"Number", "text":"six", "hide":false},
           { "category":"Number", "text":"seven", "hide":false},
           { "category":"Number", "text":"eight", "hide":false},
           { "category":"Number", "text":"nine", "hide":false},
           { "category":"Number", "text":"ten", "hide":false},
           { "category":"Number", "text":"eleven", "hide":false},
           { "category":"Number", "text":"twelve", "hide":false},
           { "category":"Number", "text":"thirteen", "hide":false},
           { "category":"Number", "text":"fourteen", "hide":false},
           { "category":"Number", "text":"fifteen", "hide":false},
           { "category":"Number", "text":"sixteen", "hide":false},
           { "category":"Number", "text":"seventeen", "hide":false},
           { "category":"Number", "text":"eighteen", "hide":false},
           { "category":"Number", "text":"nineteen", "hide":false},
           { "category":"Number", "text":"twenty", "hide":false},
           { "category":"Number", "text":"thirty", "hide":false},
           { "category":"Number", "text":"forty", "hide":false},
           { "category":"Number", "text":"fifty", "hide":false},
           { "category":"Number", "text":"sixty", "hide":false},
           { "category":"Number", "text":"seventy", "hide":false},
           { "category":"Number", "text":"eight", "hide":false},
           { "category":"Number", "text":"ninety", "hide":false},
           { "category":"Number", "text":"hundred", "hide":false},
           { "category":"Number", "text":"thousand", "hide":false},
           { "category":"Question", "text":"how", "hide":false},
           { "category":"Question", "text":"what", "hide":false},
           { "category":"Question", "text":"what's", "hide":false},
           { "category":"Question", "text":"when", "hide":false},
           { "category":"Question", "text":"where", "hide":false},
           { "category":"Question", "text":"where's", "hide":false},
           { "category":"Question", "text":"which", "hide":false},
           { "category":"Question", "text":"who", "hide":false},
           { "category":"Question", "text":"why", "hide":false},
           { "category":"Preposition", "text":"about", "hide":false},
           { "category":"Preposition", "text":"across", "hide":false},
           { "category":"Preposition", "text":"after", "hide":false},
           { "category":"Preposition", "text":"around", "hide":false},
           { "category":"Preposition", "text":"at", "hide":false},
           { "category":"Preposition", "text":"back", "hide":false},
           { "category":"Preposition", "text":"before", "hide":false},
           { "category":"Preposition", "text":"behind", "hide":false},
           { "category":"Preposition", "text":"beside", "hide":false},
           { "category":"Preposition", "text":"between", "hide":false},
           { "category":"Preposition", "text":"bottom", "hide":false},
           { "category":"Preposition", "text":"by", "hide":false},
           { "category":"Preposition", "text":"down", "hide":false},
           { "category":"Preposition", "text":"from", "hide":false},
           { "category":"Preposition", "text":"for", "hide":false},
           { "category":"Preposition", "text":"front", "hide":false},
           { "category":"Preposition", "text":"in", "hide":false},
           { "category":"Preposition", "text":"inside", "hide":false},
           { "category":"Preposition", "text":"into", "hide":false},
           { "category":"Preposition", "text":"middle", "hide":false},
           { "category":"Preposition", "text":"next to", "hide":false},
           { "category":"Preposition", "text":"of", "hide":false},
           { "category":"Preposition", "text":"off", "hide":false},
           { "category":"Preposition", "text":"on", "hide":false},
           { "category":"Preposition", "text":"out", "hide":false},
           { "category":"Preposition", "text":"outside", "hide":false},
           { "category":"Preposition", "text":"over", "hide":false},
           { "category":"Preposition", "text":"through", "hide":false},
           { "category":"Preposition", "text":"to", "hide":false},
           { "category":"Preposition", "text":"top", "hide":false},
           { "category":"Preposition", "text":"under", "hide":false},
           { "category":"Preposition", "text":"up", "hide":false},
           { "category":"Determiner", "text":"a", "hide":false},
           { "category":"Determiner", "text":"all", "hide":false},
           { "category":"Determiner", "text":"an", "hide":false},
           { "category":"Determiner", "text":"any", "hide":false},
           { "category":"Determiner", "text":"both", "hide":false},
           { "category":"Determiner", "text":"each", "hide":false},
           { "category":"Determiner", "text":"every", "hide":false},
           { "category":"Determiner", "text":"no", "hide":false},
           { "category":"Determiner", "text":"none", "hide":false},
           { "category":"Determiner", "text":"some", "hide":false},
           { "category":"Determiner", "text":"that", "hide":false},
           { "category":"Determiner", "text":"that's", "hide":false},
           { "category":"Determiner", "text":"the", "hide":false},
           { "category":"Determiner", "text":"these", "hide":false},
           { "category":"Determiner", "text":"this", "hide":false},
           { "category":"Determiner", "text":"those", "hide":false},
           { "category":"Determiner", "text":"thing", "hide":false},
           { "category":"Determiner", "text":"things", "hide":false},
           { "category":"Determiner", "text":"body", "hide":false},
           { "category":"Determiner", "text":"one", "hide":false},
           { "category":"Determiner", "text":"time", "hide":false},
           { "category":"Determiner", "text":"way", "hide":false},
           { "category":"Determiner", "text":"where", "hide":false},
           { "category":"Determiner", "text":"and", "hide":false},
           { "category":"Determiner", "text":"as", "hide":false},
           { "category":"Determiner", "text":"because", "hide":false},
           { "category":"Determiner", "text":"but", "hide":false},
           { "category":"Determiner", "text":"if", "hide":false},
           { "category":"Determiner", "text":"or", "hide":false},
           { "category":"Determiner", "text":"still", "hide":false},
           { "category":"Determiner", "text":"than", "hide":false},
           { "category":"Determiner", "text":"though", "hide":false},
           { "category":"Determiner", "text":"unless", "hide":false},
           { "category":"Determiner", "text":"until", "hide":false},
           { "category":"Determiner", "text":"with", "hide":false},
           { "category":"Conjunct", "text":"and", "hide":false},
           { "category":"Conjunct", "text":"as", "hide":false},
           { "category":"Conjunct", "text":"because", "hide":false},
           { "category":"Conjunct", "text":"but", "hide":false},
           { "category":"Conjunct", "text":"if", "hide":false},
           { "category":"Conjunct", "text":"or", "hide":false},
           { "category":"Conjunct", "text":"still", "hide":false},
           { "category":"Conjunct", "text":"than", "hide":false},
           { "category":"Conjunct", "text":"though", "hide":false},
           { "category":"Conjunct", "text":"unless", "hide":false},
           { "category":"Conjunct", "text":"until", "hide":false},
           { "category":"Conjunct", "text":"with", "hide":false},
           { "category":"Interject", "text":"Hello", "hide":false},
           { "category":"Interject", "text":"Hey", "hide":false},
           { "category":"Interject", "text":"Hi", "hide":false},
           { "category":"Interject", "text":"Ha", "hide":false},
           { "category":"Interject", "text":"Because'", "hide":false},
           { "category":"Interject", "text":"Bye", "hide":false},
           { "category":"Interject", "text":"Oh", "hide":false},
           { "category":"Interject", "text":"bother", "hide":false},
           { "category":"Interject", "text":"be careful", "hide":false},
           { "category":"Interject", "text":"awesome", "hide":false},
           { "category":"Interject", "text":"crazy", "hide":false},
           { "category":"Interject", "text":"definitely", "hide":false},
           { "category":"Interject", "text":"ah", "hide":false},
           { "category":"Interject", "text":"er", "hide":false},
           { "category":"Interject", "text":"excuse me", "hide":false},
           { "category":"Interject", "text":"huh", "hide":false},
           { "category":"Interject", "text":"OK", "hide":false},
           { "category":"Interject", "text":"mmm", "hide":false},
           { "category":"Interject", "text":"ooh", "hide":false},
           { "category":"Interject", "text":"let's", "hide":false},
           { "category":"Interject", "text":"nah", "hide":false},
           { "category":"Interject", "text":"no", "hide":false},
           { "category":"Interject", "text":"No way", "hide":false},
           { "category":"Interject", "text":"aw", "hide":false},
           { "category":"Interject", "text":"Oops!", "hide":false},
           { "category":"Interject", "text":"Ouch!", "hide":false},
           { "category":"Interject", "text":"please", "hide":false},
           { "category":"Interject", "text":"sorry", "hide":false},
           { "category":"Interject", "text":"thanks", "hide":false},
           { "category":"Interject", "text":"Uh-oh", "hide":false},
           { "category":"Interject", "text":"well", "hide":false},
           { "category":"Interject", "text":"whatever", "hide":false},
           { "category":"Interject", "text":"yeah", "hide":false},
           { "category":"Interject", "text":"Yep", "hide":false},
           { "category":"Interject", "text":"yes", "hide":false},
           { "category":"Interject", "text":"Yay!", "hide":false},
           { "category":"Interject", "text":"Yikes!", "hide":false},
           { "category":"Interject", "text":"Your welcome", "hide":false},
           { "category":"Interject", "text":"yuk", "hide":false},
           { "category":"Interject", "text":"yum", "hide":false},
           { "category":"Dolch 1", "text":"animal", "hide":false},
           { "category":"Dolch 1", "text":"bag", "hide":false},
           { "category":"Dolch 1", "text":"ball", "hide":false},
           { "category":"Dolch 1", "text":"bathroom", "hide":false},
           { "category":"Dolch 1", "text":"bear'", "hide":false},
           { "category":"Dolch 1", "text":"bed", "hide":false},
           { "category":"Dolch 1", "text":"bedroom", "hide":false},
           { "category":"Dolch 1", "text":"bird", "hide":false},
           { "category":"Dolch 1", "text":"birds", "hide":false},
           { "category":"Dolch 1", "text":"birthday", "hide":false},
           { "category":"Dolch 1", "text":"boat", "hide":false},
           { "category":"Dolch 1", "text":"book", "hide":false},
           { "category":"Dolch 1", "text":"box", "hide":false},
           { "category":"Dolch 1", "text":"bus", "hide":false},
           { "category":"Dolch 1", "text":"camp", "hide":false},
           { "category":"Dolch 1", "text":"car", "hide":false},
           { "category":"Dolch 1", "text":"card", "hide":false},
           { "category":"Dolch 1", "text":"cat", "hide":false},
           { "category":"Dolch 1", "text":"chair", "hide":false},
           { "category":"Dolch 1", "text":"chapter", "hide":false},
           { "category":"Dolch 1", "text":"Christmas", "hide":false},
           { "category":"Dolch 1", "text":"circle", "hide":false},
           { "category":"Dolch 1", "text":"class", "hide":false},
           { "category":"Dolch 1", "text":"comb", "hide":false},
           { "category":"Dolch 1", "text":"computer", "hide":false},
           { "category":"Dolch 1", "text":"cup", "hide":false},
           { "category":"Dolch 1", "text":"desk", "hide":false},
           { "category":"Dolch 1", "text":"dinner", "hide":false},
           { "category":"Dolch 1", "text":"dog", "hide":false},
           { "category":"Dolch 1", "text":"door", "hide":false},
           { "category":"Dolch 1", "text":"duck", "hide":false},
           { "category":"Dolch 1", "text":"ear", "hide":false},
           { "category":"Dolch 1", "text":"egg", "hide":false},
           { "category":"Dolch 1", "text":"eye", "hide":false},
           { "category":"Dolch 1", "text":"finger", "hide":false},
           { "category":"Dolch 1", "text":"fire", "hide":false},
           { "category":"Dolch 1", "text":"food", "hide":false},
           { "category":"Dolch 1", "text":"foot", "hide":false},
           { "category":"Dolch 1", "text":"fun", "hide":false},
           { "category":"Dolch 1", "text":"game", "hide":false},
           { "category":"Dolch 2", "text":"glasses", "hide":false},
           { "category":"Dolch 2", "text":"hair", "hide":false},
           { "category":"Dolch 2", "text":"hand", "hide":false},
           { "category":"Dolch 2", "text":"head", "hide":false},
           { "category":"Dolch 2", "text":"hill'", "hide":false},
           { "category":"Dolch 2", "text":"hip", "hide":false},
           { "category":"Dolch 2", "text":"home", "hide":false},
           { "category":"Dolch 2", "text":"house", "hide":false},
           { "category":"Dolch 2", "text":"idea", "hide":false},
           { "category":"Dolch 2", "text":"job", "hide":false},
           { "category":"Dolch 2", "text":"journal", "hide":false},
           { "category":"Dolch 2", "text":"juice", "hide":false},
           { "category":"Dolch 2", "text":"kitchen", "hide":false},
           { "category":"Dolch 2", "text":"knee", "hide":false},
           { "category":"Dolch 2", "text":"leg", "hide":false},
           { "category":"Dolch 2", "text":"lesson", "hide":false},
           { "category":"Dolch 2", "text":"lunch", "hide":false},
           { "category":"Dolch 2", "text":"money", "hide":false},
           { "category":"Dolch 2", "text":"mouth", "hide":false},
           { "category":"Dolch 2", "text":"music", "hide":false},
           { "category":"Dolch 2", "text":"name", "hide":false},
           { "category":"Dolch 2", "text":"napkin", "hide":false},
           { "category":"Dolch 2", "text":"nature", "hide":false},
           { "category":"Dolch 2", "text":"neck", "hide":false},
           { "category":"Dolch 2", "text":"nest", "hide":false},
           { "category":"Dolch 2", "text":"nose", "hide":false},
           { "category":"Dolch 2", "text":"number", "hide":false},
           { "category":"Dolch 2", "text":"paper", "hide":false},
           { "category":"Dolch 2", "text":"part", "hide":false},
           { "category":"Dolch 2", "text":"party", "hide":false},
           { "category":"Dolch 2", "text":"pet", "hide":false},
           { "category":"Dolch 2", "text":"picture", "hide":false},
           { "category":"Dolch 2", "text":"piece", "hide":false},
           { "category":"Dolch 2", "text":"place", "hide":false},
           { "category":"Dolch 2", "text":"problem", "hide":false},
           { "category":"Dolch 2", "text":"question", "hide":false},
           { "category":"Dolch 2", "text":"road", "hide":false},
           { "category":"Dolch 2", "text":"room", "hide":false},
           { "category":"Dolch 2", "text":"school", "hide":false},
           { "category":"Dolch 2", "text":"shape", "hide":false},
           { "category":"Dolch 3", "text":"side", "hide":false},
           { "category":"Dolch 3", "text":"snack", "hide":false},
           { "category":"Dolch 3", "text":"story", "hide":false},
           { "category":"Dolch 3", "text":"stuff", "hide":false},
           { "category":"Dolch 3", "text":"supper'", "hide":false},
           { "category":"Dolch 3", "text":"swing", "hide":false},
           { "category":"Dolch 3", "text":"tape", "hide":false},
           { "category":"Dolch 3", "text":"taxi", "hide":false},
           { "category":"Dolch 3", "text":"test", "hide":false},
           { "category":"Dolch 3", "text":"therapy", "hide":false},
           { "category":"Dolch 3", "text":"thing", "hide":false},
           { "category":"Dolch 3", "text":"things", "hide":false},
           { "category":"Dolch 3", "text":"time", "hide":false},
           { "category":"Dolch 3", "text":"toy", "hide":false},
           { "category":"Dolch 3", "text":"toys", "hide":false},
           { "category":"Dolch 3", "text":"town", "hide":false},
           { "category":"Dolch 3", "text":"tree", "hide":false},
           { "category":"Dolch 3", "text":"trees", "hide":false},
           { "category":"Dolch 3", "text":"trouble", "hide":false},
           { "category":"Dolch 3", "text":"tv", "hide":false},
           { "category":"Dolch 3", "text":"van", "hide":false},
           { "category":"Dolch 3", "text":"water", "hide":false},
           { "category":"Dolch 3", "text":"way", "hide":false},
           { "category":"Dolch 3", "text":"world", "hide":false},
           { "category":"Colour", "text":"black", "hide":false},
           { "category":"Colour", "text":"blue", "hide":false},
           { "category":"Colour", "text":"brown", "hide":false},
           { "category":"Colour", "text":"green", "hide":false},
           { "category":"Colour", "text":"grey", "hide":false},
           { "category":"Colour", "text":"orange", "hide":false},
           { "category":"Colour", "text":"pink", "hide":false},
           { "category":"Colour", "text":"purple", "hide":false},
           { "category":"Colour", "text":"red", "hide":false},
           { "category":"Colour", "text":"yellow", "hide":false},
           { "category":"Colour", "text":"white", "hide":false},
        ];
        return wordService;
  });