function GridCtrl($scope){
	
	
	$scope.imageGrid = [
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'link', url: 'http://placehold.it/50x50', link: 'http://imedia-ventures.com/webAAC/secondpage.html'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'},
	       {type:'speak', url: 'http://placehold.it/50x50'}
	       ];
	
}