function GridCtrl($scope){
	
	
	$scope.imageGrid = [
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'link', url: 'http://placehold.it/50x50', link: 'http://imedia-ventures.com/webAAC/secondpage.html', text:'drink'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'want'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'You'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'},
	       {type:'speak', url: 'http://placehold.it/50x50', link:'#', text:'I'}
	       ];
	
}